version: '3.9'

services:
  nginx:
    image: nginx:1.20.2-alpine
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - ./src:/api
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8080:8080
    command:
      "air -c .air.toml"
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - ./docker/db/initdb:/docker-entrypoint-initdb.d
      - db-store:/var/lib/mysql
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_api
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  db-store:
    
    